name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -m pip install --upgrade pip setuptools wheel build
      - run: pip install . -r requirements.txt
      - run: python -m build .
      - run: doit ci_python
  black-formatting-check:
    name: Check formatting
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
